language: node_js
node_js:
  - "10.7"

notifications:
  email: false

# push to branches only trigger on master (merge pr)
branches:
  only:
    - master

# install & test
install:
  - yarn

# build for deployment
before_deploy:
  - yarn build

# deploy to firebase
deploy:
  - provider: firebase
    token:
      secure: $FIREBASE_TOKEN
    project: $PROJECT_ID
    skip_cleanup: true
    on:
      branch: master
