language: node_js
node_js:
  - "9.4"
notifications:
  email: false
script:
  - echo "Deploying!"
install:
  - yarn
  - yarn build
  - npm install -g firebase-tools
after_success:
  - firebase deploy --only functions --project $PROJECT_ID --token $FIREBASE_TOKEN