language: node_js
node_js:
  - "10.7"

notifications:
  email: false

# push to branches only trigger on master (merge pr)
branches:
  only:
    - master

# install & test
install:
  - yarn

# deploy to firebase
deploy:
  provider: script
  script: bash scripts/deploy.sh $PROJECT_ID $FIREBASE_TOKEN
  skip_cleanup: true
  on:
    branch: master
