language: node_js
node_js:
  - "10.7"

notifications:
  email: false

# push to branches only trigger on master (merge pr)
branches:
  only:
    - master

# install & test
install:
  - yarn
  - test $TRAVIS_BRANCH = "master" && yarn build
  - test $TRAVIS_BRANCH = "master" && npm install -g firebase-tools

# deploy to firebase
after_success:
  - test $TRAVIS_BRANCH = "master" && firebase deploy --only functions --project $PROJECT_ID --token $FIREBASE_TOKEN
