name: On Master

on:
  push:
    branches: [master]

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Run Coverage
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn --frozen-lockfile
      - run: yarn test
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    name: Build Project
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: build

  deploy:
    runs-on: ubuntu-latest
    name: Deploy Project
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
