name: On Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check Lint
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '12.x'
      - run: yarn --frozen-lockfile
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    name: Run Tests
    needs: [lint]
    steps:
      - uses: actions/checkout@v2
      - run: yarn --frozen-lockfile
      - run: yarn test
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    name: Build Project
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - run: yarn --frozen-lockfile
      - run: yarn build
