name: On Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check Lint
    steps:
      - uses: actions/checkout@v2
      - run: yarn --ignore-engines
      - run: yarn lint --ignore-engines

  test:
    runs-on: ubuntu-latest
    name: Run Tests
    needs: [lint]
    steps:
      - uses: actions/checkout@v2
      - run: yarn --ignore-engines
      - run: yarn test --ignore-engines
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    name: Build Project
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - run: yarn --ignore-engines
      - run: yarn build --ignore-engines
